language: java

services:
  - postgresql

env:
  global:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/patients-test
    - SPRING_DATASOURCE_PASSWORD=
    - SPRING_DATASOURCE_USER=postgres

before_script:
  - psql -c 'create database patients_test;' -U postgres

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


