version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "patients_postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=patients
      - POSTGRES_PASSWORD=development1234
      - POSTGRES_DB=patients
  test-db:
    image: "postgres:11"
    container_name: "patients_test_postgres"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=patients
      - POSTGRES_PASSWORD=development1234
      - POSTGRES_DB=patients-test

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/patients
    volumes:
      - .:/code